### ISSUE TITLE
variable type should change to choices 

### ISSUE THREAD

**Issue by jmahabali** [sleepepi/ccshs-data-dictionary#33]
- [ ] `waistge75`
- [ ] `waistge90`
- [ ] `waistgt75`
- [ ] `waistgt90`
- [ ] `sleepy`
- [ ] `sleepy_adult`

**Comment by michellereid** [comment]
@jmahabali  All of these variables have yes/no option choices... did you mean to say something else?

https://www.sleepdata.org/datasets/ccshs/variables/waistge75
https://www.sleepdata.org/datasets/ccshs/variables/waistge90
https://www.sleepdata.org/datasets/ccshs/variables/waistgt75
https://www.sleepdata.org/datasets/ccshs/variables/waistgt90
https://www.sleepdata.org/datasets/ccshs/variables/sleepy
https://www.sleepdata.org/datasets/ccshs/variables/sleepy_adult

**Comment by jmahabali** [comment]
Looks good
