### ISSUE TITLE
Re-add CDE labels for a handful of variables

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/ccshs-data-dictionary#39]

**Comment by michellereid** [comment]
Referenced in commits [056d30a](https://github.com/sleepepi/ccshs-data-dictionary/commit/056d30afb63f259ea02ecfc837c066b2a9021da0) and [8a015ee](https://github.com/sleepepi/ccshs-data-dictionary/commit/8a015eea7671416f00f6ea54dd8ac91642933a0b)
